on:
  push:
  pull_request:

name: "Lint Code"
jobs: 
  lint-code:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@master
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: |
          install.packages(c("httr", "docopt", "styler"), type = "binary")
        shell: Rscript {0}
      - name: Lint package
        run: styler::style_dir("src")
        shell: Rscript {0}
      - name: Commit and push changes
        run: |
          if [[ `git status --porcelain` ]]; then
           git config user.name 'github-actions[bot]'
           git config user.email 'github-actions[bot]@users.noreply.github.com'
           git add -A
           git commit -m "Lint package"
           git push
          fi